<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0-android</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>Geekhonize.Android</RootNamespace>
    <AssemblyName>GeekhonizeLauncher.Android</AssemblyName>
    <ApplicationId>top.geekhonize.launcher</ApplicationId>
    <ApplicationTitle>BREAKFRONT 启动器</ApplicationTitle>
    <ApplicationDisplayVersion>0.1.0</ApplicationDisplayVersion>
    <SupportedOSPlatformVersion>24</SupportedOSPlatformVersion>
    <AndroidPackageFormats>apk</AndroidPackageFormats>
    <AndroidEnableProfiledAot>false</AndroidEnableProfiledAot>
    <AvaloniaUseCompiledBindingsByDefault>false</AvaloniaUseCompiledBindingsByDefault>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia" Version="11.3.2" />
    <PackageReference Include="Avalonia.Themes.Fluent" Version="11.3.2" />
    <PackageReference Include="Avalonia.Fonts.Inter" Version="11.3.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../Geekhonize.App/Geekhonize.App.csproj" />
  </ItemGroup>
</Project>
