<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>Geekhonize.Shared</RootNamespace>
    <AssemblyName>Geekhonize.Shared</AssemblyName>
  </PropertyGroup>
</Project>
